'use server';
/**
 * @fileOverview Provides AI-generated sales insights and actionable recommendations for restaurant admins.
 *
 * - getAiSalesInsights - A function that fetches AI-powered sales insights.
 * - AiSalesInsightsInput - The input type for the getAiSalesInsights function.
 * - AiSalesInsightsOutput - The return type for the getAiSalesInsights function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SalesRecordSchema = z.object({
  orderId: z.string().describe('Unique identifier for the order.'),
  timestamp: z.string().datetime().describe('ISO 8601 formatted timestamp of when the order was placed.'),
  items: z.array(
    z.object({
      itemId: z.string().describe('Unique identifier for the menu item.'),
      itemName: z.string().describe('Name of the menu item.'),
      quantity: z.number().int().positive().describe('Quantity of the item sold.'),
      price: z.number().positive().describe('Price of a single unit of the item.'),
    })
  ).describe('List of items included in the order.'),
  totalAmount: z.number().positive().describe('Total monetary amount of the order.'),
});

const AiSalesInsightsInputSchema = z.object({
  salesData: z.array(SalesRecordSchema).describe('Raw sales transaction data for analysis.'),
  timeframe: z.string().optional().describe('Optional: Specific timeframe for analysis (e.g., "last month", "last quarter").'),
  additionalContext: z.string().optional().describe('Optional: Any specific questions or areas of focus for the AI.'),
});
export type AiSalesInsightsInput = z.infer<typeof AiSalesInsightsInputSchema>;

const AiSalesInsightsOutputSchema = z.object({
  overallPerformanceSummary: z.string().describe('A concise summary of the restaurant\'s overall sales performance.'),
  keyPerformanceIndicators: z.object({
    totalRevenue: z.number().describe('Total revenue generated.'),
    averageOrderValue: z.number().describe('Average value of each order.'),
    numberOfOrders: z.number().int().describe('Total number of orders processed.'),
    revenueGrowthRate: z.number().optional().describe('Percentage growth or decline in revenue over the timeframe.'),
  }).describe('Key metrics summarizing sales performance.'),
  bestSellingItems: z.array(
    z.object({
      itemName: z.string().describe('Name of the best-selling item.'),
      totalQuantitySold: z.number().int().describe('Total quantity of this item sold.'),
      totalRevenueGenerated: z.number().describe('Total revenue generated by this item.'),
    })
  ).describe('List of top-performing menu items based on sales volume and revenue.'),
  menuOptimizationSuggestions: z.array(z.string()).describe('Actionable suggestions for optimizing the menu (e.g., pricing adjustments, item bundling, removal of underperforming items).'),
  promotionalStrategies: z.array(z.string()).describe('Recommendations for effective promotional campaigns (e.g., happy hour deals, loyalty programs, seasonal specials).'),
  performanceTrends: z.array(z.string()).describe('Identified trends in sales data (e.g., peak hours, seasonal variations, weekday vs. weekend performance).'),
  actionableRecommendations: z.array(z.string()).describe('Specific, practical steps the restaurant admin can take to improve sales and operational efficiency.'),
});
export type AiSalesInsightsOutput = z.infer<typeof AiSalesInsightsOutputSchema>;

export async function getAiSalesInsights(input: AiSalesInsightsInput): Promise<AiSalesInsightsOutput> {
  return aiSalesInsightsFlow(input);
}

const aiSalesInsightsPrompt = ai.definePrompt({
  name: 'aiSalesInsightsPrompt',
  input: { schema: AiSalesInsightsInputSchema },
  output: { schema: AiSalesInsightsOutputSchema },
  prompt: `You are an expert restaurant business analyst and marketing strategist. Your task is to analyze the provided sales data for a restaurant and generate comprehensive, actionable insights and recommendations.

Analyze the following sales data:

Sales Data: {{{JSON.stringify salesData}}}

${'{{#if timeframe}}'}Analyze the data specifically for the timeframe: {{{timeframe}}}{"{{/if}}"}
${'{{#if additionalContext}}'}Consider the following additional context or questions from the restaurant admin: {{{additionalContext}}}{"{{/if}}"}

Based on the analysis, provide:
1.  An overall performance summary.
2.  Key performance indicators (KPIs) like total revenue, average order value, number of orders, and revenue growth rate.
3.  A list of best-selling items, including quantity sold and revenue generated.
4.  Specific suggestions for menu optimization.
5.  Creative and effective promotional strategies.
6.  Identified performance trends (e.g., peak times, seasonal shifts).
7.  Overall actionable recommendations to increase revenue and improve operational efficiency.

Ensure your response is clear, concise, and directly addresses the output schema provided.`,
});

const aiSalesInsightsFlow = ai.defineFlow(
  {
    name: 'aiSalesInsightsFlow',
    inputSchema: AiSalesInsightsInputSchema,
    outputSchema: AiSalesInsightsOutputSchema,
  },
  async (input) => {
    const { output } = await aiSalesInsightsPrompt(input);
    if (!output) {
      throw new Error('Failed to generate AI sales insights.');
    }
    return output;
  }
);
