
export interface City {
  id: string;
  name: string;
}

export interface State {
  id: string;
  name: string;
  cities: City[];
}

export interface CountryRegions {
  [countryCode: string]: State[];
}

export const REGIONS_DATA: CountryRegions = {
  AU: [
    { id: 'nsw', name: 'New South Wales', cities: [{ id: 'sydney', name: 'Sydney' }, { id: 'newcastle', name: 'Newcastle' }, { id: 'wollongong', name: 'Wollongong' }] },
    { id: 'vic', name: 'Victoria', cities: [{ id: 'melbourne', name: 'Melbourne' }, { id: 'geelong', name: 'Geelong' }, { id: 'ballarat', name: 'Ballarat' }] },
    { id: 'qld', name: 'Queensland', cities: [{ id: 'brisbane', name: 'Brisbane' }, { id: 'goldcoast', name: 'Gold Coast' }, { id: 'cairns', name: 'Cairns' }] },
    { id: 'wa', name: 'Western Australia', cities: [{ id: 'perth', name: 'Perth' }, { id: 'fremantle', name: 'Freemantle' }, { id: 'bunbury', name: 'Bunbury' }] },
    { id: 'sa', name: 'South Australia', cities: [{ id: 'adelaide', name: 'Adelaide' }, { id: 'mountgambier', name: 'Mount Gambier' }] },
    { id: 'tas', name: 'Tasmania', cities: [{ id: 'hobart', name: 'Hobart' }, { id: 'launceston', name: 'Launceston' }] },
    { id: 'act', name: 'Australian Capital Territory', cities: [{ id: 'canberra', name: 'Canberra' }] },
    { id: 'nt', name: 'Northern Territory', cities: [{ id: 'darwin', name: 'Darwin' }, { id: 'alicesprings', name: 'Alice Springs' }] },
  ],
  GB: [
    { id: 'eng', name: 'England', cities: [{ id: 'london', name: 'London' }, { id: 'manchester', name: 'Manchester' }, { id: 'birmingham', name: 'Birmingham' }, { id: 'liverpool', name: 'Liverpool' }] },
    { id: 'sct', name: 'Scotland', cities: [{ id: 'edinburgh', name: 'Edinburgh' }, { id: 'glasgow', name: 'Glasgow' }, { id: 'aberdeen', name: 'Aberdeen' }] },
    { id: 'wls', name: 'Wales', cities: [{ id: 'cardiff', name: 'Cardiff' }, { id: 'swansea', name: 'Swansea' }] },
    { id: 'nir', name: 'Northern Ireland', cities: [{ id: 'belfast', name: 'Belfast' }, { id: 'derry', name: 'Derry' }] },
  ],
  US: [
    { id: 'al', name: 'Alabama', cities: [{ id: 'montgomery', name: 'Montgomery' }, { id: 'birmingham-us', name: 'Birmingham' }] },
    { id: 'ak', name: 'Alaska', cities: [{ id: 'juneau', name: 'Juneau' }, { id: 'anchorage', name: 'Anchorage' }] },
    { id: 'az', name: 'Arizona', cities: [{ id: 'phoenix', name: 'Phoenix' }] },
    { id: 'ar', name: 'Arkansas', cities: [{ id: 'littlerock', name: 'Little Rock' }] },
    { id: 'ca', name: 'California', cities: [{ id: 'la', name: 'Los Angeles' }, { id: 'sf', name: 'San Francisco' }, { id: 'sd', name: 'San Diego' }] },
    { id: 'co', name: 'Colorado', cities: [{ id: 'denver', name: 'Denver' }] },
    { id: 'ct', name: 'Connecticut', cities: [{ id: 'hartford', name: 'Hartford' }] },
    { id: 'de', name: 'Delaware', cities: [{ id: 'dover', name: 'Dover' }] },
    { id: 'fl', name: 'Florida', cities: [{ id: 'miami', name: 'Miami' }, { id: 'orlando', name: 'Orlando' }, { id: 'tampa', name: 'Tampa' }] },
    { id: 'ga', name: 'Georgia', cities: [{ id: 'atlanta', name: 'Atlanta' }] },
    { id: 'hi', name: 'Hawaii', cities: [{ id: 'honolulu', name: 'Honolulu' }] },
    { id: 'id', name: 'Idaho', cities: [{ id: 'boise', name: 'Boise' }] },
    { id: 'il', name: 'Illinois', cities: [{ id: 'chicago', name: 'Chicago' }] },
    { id: 'in', name: 'Indiana', cities: [{ id: 'indianapolis', name: 'Indianapolis' }] },
    { id: 'ia', name: 'Iowa', cities: [{ id: 'desmoines', name: 'Des Moines' }] },
    { id: 'ks', name: 'Kansas', cities: [{ id: 'topeka', name: 'Topeka' }] },
    { id: 'ky', name: 'Kentucky', cities: [{ id: 'frankfort', name: 'Frankfort' }] },
    { id: 'la-us', name: 'Louisiana', cities: [{ id: 'batonrouge', name: 'Baton Rouge' }] },
    { id: 'me', name: 'Maine', cities: [{ id: 'augusta', name: 'Augusta' }] },
    { id: 'md', name: 'Maryland', cities: [{ id: 'annapolis', name: 'Annapolis' }] },
    { id: 'ma', name: 'Massachusetts', cities: [{ id: 'boston', name: 'Boston' }] },
    { id: 'mi', name: 'Michigan', cities: [{ id: 'lansing', name: 'Lansing' }] },
    { id: 'mn', name: 'Minnesota', cities: [{ id: 'stpaul', name: 'St. Paul' }] },
    { id: 'ms', name: 'Mississippi', cities: [{ id: 'jackson', name: 'Jackson' }] },
    { id: 'mo', name: 'Missouri', cities: [{ id: 'jeffersoncity', name: 'Jefferson City' }] },
    { id: 'mt', name: 'Montana', cities: [{ id: 'helena', name: 'Helena' }] },
    { id: 'ne', name: 'Nebraska', cities: [{ id: 'lincoln', name: 'Lincoln' }] },
    { id: 'nv', name: 'Nevada', cities: [{ id: 'carsoncity', name: 'Carson City' }, { id: 'lasvegas', name: 'Las Vegas' }] },
    { id: 'nh', name: 'New Hampshire', cities: [{ id: 'concord', name: 'Concord' }] },
    { id: 'nj', name: 'New Jersey', cities: [{ id: 'trenton', name: 'Trenton' }] },
    { id: 'nm', name: 'New Mexico', cities: [{ id: 'santafe', name: 'Santa Fe' }] },
    { id: 'ny', name: 'New York', cities: [{ id: 'albany-us', name: 'Albany' }, { id: 'nyc', name: 'New York City' }] },
    { id: 'nc', name: 'North Carolina', cities: [{ id: 'raleigh', name: 'Raleigh' }] },
    { id: 'nd', name: 'North Dakota', cities: [{ id: 'bismarck', name: 'Bismarck' }] },
    { id: 'oh', name: 'Ohio', cities: [{ id: 'columbus', name: 'Columbus' }] },
    { id: 'ok', name: 'Oklahoma', cities: [{ id: 'oklahomacity', name: 'Oklahoma City' }] },
    { id: 'or', name: 'Oregon', cities: [{ id: 'salem', name: 'Salem' }] },
    { id: 'pa', name: 'Pennsylvania', cities: [{ id: 'harrisburg', name: 'Harrisburg' }] },
    { id: 'ri', name: 'Rhode Island', cities: [{ id: 'providence', name: 'Providence' }] },
    { id: 'sc', name: 'South Carolina', cities: [{ id: 'columbia', name: 'Columbia' }] },
    { id: 'sd', name: 'South Dakota', cities: [{ id: 'pierre', name: 'Pierre' }] },
    { id: 'tn', name: 'Tennessee', cities: [{ id: 'nashville', name: 'Nashville' }] },
    { id: 'tx', name: 'Texas', cities: [{ id: 'austin', name: 'Austin' }, { id: 'houston', name: 'Houston' }, { id: 'dallas', name: 'Dallas' }] },
    { id: 'ut', name: 'Utah', cities: [{ id: 'saltlakecity', name: 'Salt Lake City' }] },
    { id: 'vt', name: 'Vermont', cities: [{ id: 'montpelier', name: 'Montpelier' }] },
    { id: 'va', name: 'Virginia', cities: [{ id: 'richmond', name: 'Richmond' }] },
    { id: 'wa-us', name: 'Washington', cities: [{ id: 'olympia', name: 'Olympia' }, { id: 'seattle', name: 'Seattle' }] },
    { id: 'wv', name: 'West Virginia', cities: [{ id: 'charleston', name: 'Charleston' }] },
    { id: 'wi', name: 'Wisconsin', cities: [{ id: 'madison', name: 'Madison' }] },
    { id: 'wy', name: 'Wyoming', cities: [{ id: 'cheyenne', name: 'Wyoming' }] },
  ],
  AE: [
    { id: 'auh', name: 'Abu Dhabi', cities: [{ id: 'auh-city', name: 'Abu Dhabi City' }, { id: 'al-ain', name: 'Al Ain' }] },
    { id: 'dxb', name: 'Dubai', cities: [{ id: 'dxb-city', name: 'Dubai City' }, { id: 'jebel-ali', name: 'Jebel Ali' }] },
    { id: 'shj', name: 'Sharjah', cities: [{ id: 'shj-city', name: 'Sharjah City' }, { id: 'khor-fakkan', name: 'Khor Fakkan' }] },
    { id: 'ajm', name: 'Ajman', cities: [{ id: 'ajm-city', name: 'Ajman City' }] },
    { id: 'uaq', name: 'Umm Al-Quwain', cities: [{ id: 'uaq-city', name: 'Umm Al-Quwain City' }] },
    { id: 'rak', name: 'Ras Al-Khaimah', cities: [{ id: 'rak-city', name: 'Ras Al-Khaimah City' }] },
    { id: 'fuj', name: 'Fujairah', cities: [{ id: 'fuj-city', name: 'Fujairah City' }] },
  ],
  SA: [
    { id: 'riy', name: 'Riyadh', cities: [{ id: 'riy-city', name: 'Riyadh City' }, { id: 'al-kharj', name: 'Al-Kharj' }] },
    { id: 'mak', name: 'Makkah', cities: [{ id: 'jeddah', name: 'Jeddah' }, { id: 'makkah-city', name: 'Makkah City' }, { id: 'taif', name: 'Taif' }] },
    { id: 'mad', name: 'Madinah', cities: [{ id: 'mad-city', name: 'Madinah City' }, { id: 'yanbu', name: 'Yanbu' }] },
    { id: 'eas', name: 'Eastern Province', cities: [{ id: 'dammam', name: 'Dammam' }, { id: 'khobar', name: 'Al Khobar' }, { id: 'dhahran', name: 'Dhahran' }] },
    { id: 'asr', name: 'Asir', cities: [{ id: 'abha', name: 'Abha' }] },
    { id: 'tab', name: 'Tabuk', cities: [{ id: 'tab-city', name: 'Tabuk City' }] },
    { id: 'hai', name: 'Hail', cities: [{ id: 'hai-city', name: 'Hail City' }] },
    { id: 'nor', name: 'Northern Borders', cities: [{ id: 'arar', name: 'Arar' }] },
    { id: 'jaz', name: 'Jazan', cities: [{ id: 'jaz-city', name: 'Jazan City' }] },
    { id: 'naj', name: 'Najran', cities: [{ id: 'naj-city', name: 'Najran City' }] },
    { id: 'bah', name: 'Al-Bahah', cities: [{ id: 'bah-city', name: 'Al-Bahah City' }] },
    { id: 'jaw', name: 'Al-Jawf', cities: [{ id: 'sakaka', name: 'Sakaka' }] },
    { id: 'qas', name: 'Al-Qassim', cities: [{ id: 'buraydah', name: 'Buraydah' }] },
  ],
  PK: [
    { id: 'pun', name: 'Punjab', cities: [{ id: 'lahore', name: 'Lahore' }, { id: 'faisalabad', name: 'Faisalabad' }, { id: 'multan', name: 'Multan' }, { id: 'rawalpindi', name: 'Rawalpindi' }] },
    { id: 'sin', name: 'Sindh', cities: [{ id: 'karachi', name: 'Karachi' }, { id: 'hyderabad', name: 'Hyderabad' }, { id: 'sukkur', name: 'Sukkur' }] },
    { id: 'kpk', name: 'Khyber Pakhtunkhwa', cities: [{ id: 'peshawar', name: 'Peshawar' }, { id: 'abbottabad', name: 'Abbottabad' }] },
    { id: 'bal', name: 'Balochistan', cities: [{ id: 'quetta', name: 'Quetta' }, { id: 'gwadar', name: 'Gwadar' }] },
    { id: 'ict', name: 'Islamabad Capital Territory', cities: [{ id: 'islamabad', name: 'Islamabad' }] },
    { id: 'ajk', name: 'Azad Jammu and Kashmir', cities: [{ id: 'muzaffarabad', name: 'Muzaffarabad' }] },
    { id: 'gb', name: 'Gilgit-Baltistan', cities: [{ id: 'gilgit', name: 'Gilgit' }] },
  ],
  NZ: [
    { id: 'auk', name: 'Auckland', cities: [{ id: 'auk-city', name: 'Auckland City' }] },
    { id: 'wlg', name: 'Wellington', cities: [{ id: 'wlg-city', name: 'Wellington City' }] },
    { id: 'can', name: 'Canterbury', cities: [{ id: 'christchurch', name: 'Christchurch' }] },
    { id: 'otg', name: 'Otago', cities: [{ id: 'dunedin', name: 'Dunedin' }, { id: 'queenstown', name: 'Queenstown' }] },
    { id: 'bay', name: 'Bay of Plenty', cities: [{ id: 'tauranga', name: 'Tauranga' }] },
    { id: 'nor-nz', name: 'Northland', cities: [{ id: 'whangarei', name: 'Whangarei' }] },
    { id: 'wai', name: 'Waikato', cities: [{ id: 'hamilton-nz', name: 'Hamilton' }] },
    { id: 'haw', name: 'Hawkes Bay', cities: [{ id: 'napier', name: 'Napier' }] },
    { id: 'man', name: 'Manawatu-Wanganui', cities: [{ id: 'palmerstonnorth', name: 'Palmerston North' }] },
    { id: 'tar', name: 'Taranaki', cities: [{ id: 'newplymouth', name: 'New Plymouth' }] },
    { id: 'gis', name: 'Gisborne', cities: [{ id: 'gis-city', name: 'Gisborne' }] },
    { id: 'tas-nz', name: 'Tasman', cities: [{ id: 'richmond-nz', name: 'Richmond' }] },
    { id: 'nel', name: 'Nelson', cities: [{ id: 'nel-city', name: 'Nelson' }] },
    { id: 'mar', name: 'Marlborough', cities: [{ id: 'blenheim', name: 'Blenheim' }] },
    { id: 'wes', name: 'West Coast', cities: [{ id: 'greymouth', name: 'Greymouth' }] },
    { id: 'sou', name: 'Southland', cities: [{ id: 'invercargill', name: 'Invercargill' }] },
  ],
  MY: [
    { id: 'jhr', name: 'Johor', cities: [{ id: 'johor-bahru', name: 'Johor Bahru' }] },
    { id: 'kdh', name: 'Kedah', cities: [{ id: 'alorsetar', name: 'Alor Setar' }] },
    { id: 'ktn', name: 'Kelantan', cities: [{ id: 'kotabharu', name: 'Kota Bharu' }] },
    { id: 'mlk', name: 'Melaka', cities: [{ id: 'melaka-city', name: 'Melaka City' }] },
    { id: 'nsn', name: 'Negeri Sembilan', cities: [{ id: 'seremban', name: 'Seremban' }] },
    { id: 'phg', name: 'Pahang', cities: [{ id: 'kuantan', name: 'Kuantan' }] },
    { id: 'prk', name: 'Perak', cities: [{ id: 'ipoh', name: 'Ipoh' }] },
    { id: 'pls', name: 'Perlis', cities: [{ id: 'kangar', name: 'Kangar' }] },
    { id: 'png', name: 'Penang', cities: [{ id: 'george-town', name: 'George Town' }, { id: 'butterworth', name: 'Butterworth' }] },
    { id: 'sbh', name: 'Sabah', cities: [{ id: 'kotakinabalu', name: 'Kota Kinabalu' }] },
    { id: 'swk', name: 'Sarawak', cities: [{ id: 'kuching', name: 'Kuching' }] },
    { id: 'sel', name: 'Selangor', cities: [{ id: 'shah-alam', name: 'Shah Alam' }, { id: 'petaling-jaya', name: 'Petaling Jaya' }] },
    { id: 'trg', name: 'Terengganu', cities: [{ id: 'kualaterengganu', name: 'Kuala Terengganu' }] },
    { id: 'kl', name: 'Kuala Lumpur', cities: [{ id: 'kl-city', name: 'Kuala Lumpur City' }] },
    { id: 'lbn', name: 'Labuan', cities: [{ id: 'victoria', name: 'Labuan Town' }] },
    { id: 'pjy', name: 'Putrajaya', cities: [{ id: 'putrajaya-city', name: 'Putrajaya' }] },
  ],
  TH: [
    { id: 'bkk', name: 'Bangkok', cities: [{ id: 'bkk-city', name: 'Bangkok City' }] },
    { id: 'chi', name: 'Chiang Mai', cities: [{ id: 'chi-city', name: 'Chiang Mai City' }] },
    { id: 'pku', name: 'Phuket', cities: [{ id: 'pku-city', name: 'Phuket City' }] },
    { id: 'cho', name: 'Chon Buri', cities: [{ id: 'pattaya', name: 'Pattaya' }] },
    { id: 'rai', name: 'Chiang Rai', cities: [{ id: 'rai-city', name: 'Chiang Rai' }] },
    { id: 'kkn', name: 'Khon Kaen', cities: [{ id: 'kkn-city', name: 'Khon Kaen' }] },
    { id: 'nrt', name: 'Nakhon Ratchasima', cities: [{ id: 'korat', name: 'Korat' }] },
    { id: 'sur', name: 'Surat Thani', cities: [{ id: 'samui', name: 'Koh Samui' }] },
    { id: 'amy', name: 'Amnat Charoen', cities: [{ id: 'amy-city', name: 'Amnat Charoen' }] },
    { id: 'atp', name: 'Ang Thong', cities: [{ id: 'atp-city', name: 'Ang Thong' }] },
    { id: 'bkk-p', name: 'Bueng Kan', cities: [{ id: 'bkk-p-city', name: 'Bueng Kan' }] },
    { id: 'bur', name: 'Buriram', cities: [{ id: 'bur-city', name: 'Buriram' }] },
    { id: 'cha', name: 'Chachoengsao', cities: [{ id: 'cha-city', name: 'Chachoengsao' }] },
    { id: 'chn', name: 'Chainat', cities: [{ id: 'chn-city', name: 'Chainat' }] },
    { id: 'cyp', name: 'Chaiyaphum', cities: [{ id: 'cyp-city', name: 'Chaiyaphum' }] },
    { id: 'cnt', name: 'Chanthaburi', cities: [{ id: 'cnt-city', name: 'Chanthaburi' }] },
    { id: 'chp', name: 'Chumphon', cities: [{ id: 'chp-city', name: 'Chumphon' }] },
    { id: 'kal', name: 'Kalasin', cities: [{ id: 'kal-city', name: 'Kalasin' }] },
    { id: 'kpt', name: 'Kamphaeng Phet', cities: [{ id: 'kpt-city', name: 'Kamphaeng Phet' }] },
    { id: 'kan', name: 'Kanchanaburi', cities: [{ id: 'kan-city', name: 'Kanchanaburi' }] },
    { id: 'kbi', name: 'Krabi', cities: [{ id: 'kbi-city', name: 'Krabi' }] },
    { id: 'lpg', name: 'Lampang', cities: [{ id: 'lpg-city', name: 'Lampang' }] },
    { id: 'lpn', name: 'Lamphun', cities: [{ id: 'lpn-city', name: 'Lamphun' }] },
    { id: 'lei', name: 'Loei', cities: [{ id: 'lei-city', name: 'Loei' }] },
    { id: 'lri', name: 'Lopburi', cities: [{ id: 'lri-city', name: 'Lopburi' }] },
    { id: 'msn', name: 'Mae Hong Son', cities: [{ id: 'msn-city', name: 'Mae Hong Son' }] },
    { id: 'mkm', name: 'Maha Sarakham', cities: [{ id: 'mkm-city', name: 'Maha Sarakham' }] },
    { id: 'mda', name: 'Mukdahan', cities: [{ id: 'mda-city', name: 'Mukdahan' }] },
    { id: 'nny', name: 'Nakhon Nayok', cities: [{ id: 'nny-city', name: 'Nakhon Nayok' }] },
    { id: 'npm', name: 'Nakhon Pathom', cities: [{ id: 'npm-city', name: 'Nakhon Pathom' }] },
    { id: 'nph', name: 'Nakhon Phanom', cities: [{ id: 'nph-city', name: 'Nakhon Phanom' }] },
    { id: 'nsw-th', name: 'Nakhon Sawan', cities: [{ id: 'nsw-th-city', name: 'Nakhon Sawan' }] },
    { id: 'nsi', name: 'Nakhon Si Thammarat', cities: [{ id: 'nsi-city', name: 'Nakhon Si Thammarat' }] },
    { id: 'nan', name: 'Nan', cities: [{ id: 'nan-city', name: 'Nan' }] },
    { id: 'nwt', name: 'Narathiwat', cities: [{ id: 'nwt-city', name: 'Narathiwat' }] },
    { id: 'nbl', name: 'Nong Bua Lamphu', cities: [{ id: 'nbl-city', name: 'Nong Bua Lamphu' }] },
    { id: 'nkh', name: 'Nong Khai', cities: [{ id: 'nkh-city', name: 'Nong Khai' }] },
    { id: 'ntb', name: 'Nonthaburi', cities: [{ id: 'ntb-city', name: 'Nonthaburi' }] },
    { id: 'pnt', name: 'Pathum Thani', cities: [{ id: 'pnt-city', name: 'Pathum Thani' }] },
    { id: 'pni', name: 'Pattani', cities: [{ id: 'pni-city', name: 'Pattani' }] },
    { id: 'pna', name: 'Phang Nga', cities: [{ id: 'pna-city', name: 'Phang Nga' }] },
    { id: 'ptl', name: 'Phatthalung', cities: [{ id: 'ptl-city', name: 'Phatthalung' }] },
    { id: 'pyao', name: 'Phayao', cities: [{ id: 'pyao-city', name: 'Phayao' }] },
    { id: 'pnb', name: 'Phetchabun', cities: [{ id: 'pnb-city', name: 'Phetchabun' }] },
    { id: 'pbi', name: 'Phetchaburi', cities: [{ id: 'pbi-city', name: 'Phetchaburi' }] },
    { id: 'pmn', name: 'Phimai', cities: [{ id: 'pmn-city', name: 'Phimai' }] },
    { id: 'pit', name: 'Phitsanulok', cities: [{ id: 'pit-city', name: 'Phitsanulok' }] },
    { id: 'pya', name: 'Phra Nakhon Si Ayutthaya', cities: [{ id: 'ayu', name: 'Ayutthaya' }] },
    { id: 'pre', name: 'Phrae', cities: [{ id: 'pre-city', name: 'Phrae' }] },
    { id: 'pcn', name: 'Prachinburi', cities: [{ id: 'pcn-city', name: 'Prachinburi' }] },
    { id: 'pkk', name: 'Prachuap Khiri Khan', cities: [{ id: 'hua-hin', name: 'Hua Hin' }] },
    { id: 'ran', name: 'Ranong', cities: [{ id: 'ran-city', name: 'Ranong' }] },
    { id: 'rat', name: 'Ratchaburi', cities: [{ id: 'rat-city', name: 'Ratchaburi' }] },
    { id: 'ray', name: 'Rayong', cities: [{ id: 'ray-city', name: 'Rayong' }] },
    { id: 'roi', name: 'Roi Et', cities: [{ id: 'roi-city', name: 'Roi Et' }] },
    { id: 'skw', name: 'Sa Kaeo', cities: [{ id: 'skw-city', name: 'Sa Kaeo' }] },
    { id: 'snk', name: 'Sakon Nakhon', cities: [{ id: 'snk-city', name: 'Sakon Nakhon' }] },
    { id: 'spk', name: 'Samut Prakan', cities: [{ id: 'spk-city', name: 'Samut Prakan' }] },
    { id: 'sps', name: 'Samut Sakhon', cities: [{ id: 'sps-city', name: 'Samut Sakhon' }] },
    { id: 'spm', name: 'Samut Songkhram', cities: [{ id: 'spm-city', name: 'Samut Songkhram' }] },
    { id: 'srb', name: 'Saraburi', cities: [{ id: 'srb-city', name: 'Saraburi' }] },
    { id: 'sat', name: 'Satun', cities: [{ id: 'sat-city', name: 'Satun' }] },
    { id: 'skr', name: 'Sing Buri', cities: [{ id: 'skr-city', name: 'Sing Buri' }] },
    { id: 'sis', name: 'Sisaket', cities: [{ id: 'sis-city', name: 'Sisaket' }] },
    { id: 'ska', name: 'Songkhla', cities: [{ id: 'hat-yai', name: 'Hat Yai' }] },
    { id: 'suk', name: 'Sukhothai', cities: [{ id: 'suk-city', name: 'Sukhothai' }] },
    { id: 'spb', name: 'Suphan Buri', cities: [{ id: 'spb-city', name: 'Suphan Buri' }] },
    { id: 'sur-p', name: 'Surin', cities: [{ id: 'sur-p-city', name: 'Surin' }] },
    { id: 'tak', name: 'Tak', cities: [{ id: 'mae-sot', name: 'Mae Sot' }] },
    { id: 'trn', name: 'Trang', cities: [{ id: 'trn-city', name: 'Trang' }] },
    { id: 'trt', name: 'Trat', cities: [{ id: 'koh-chang', name: 'Koh Chang' }] },
    { id: 'ubn', name: 'Ubon Ratchathani', cities: [{ id: 'ubn-city', name: 'Ubon Ratchathani' }] },
    { id: 'udn', name: 'Udon Thani', cities: [{ id: 'udn-city', name: 'Udon Thani' }] },
    { id: 'uth', name: 'Uthai Thani', cities: [{ id: 'uth-city', name: 'Uthai Thani' }] },
    { id: 'utt', name: 'Uttaradit', cities: [{ id: 'utt-city', name: 'Uttaradit' }] },
    { id: 'yla', name: 'Yala', cities: [{ id: 'yla-city', name: 'Yala' }] },
    { id: 'yst', name: 'Yasothon', cities: [{ id: 'yst-city', name: 'Yasothon' }] },
  ],
  SG: [
    { id: 'cen', name: 'Central Region', cities: [{ id: 'singapore-city', name: 'Singapore' }] },
    { id: 'est', name: 'East Region', cities: [{ id: 'tampines', name: 'Tampines' }] },
    { id: 'wst', name: 'West Region', cities: [{ id: 'jurong', name: 'Jurong' }] },
    { id: 'nor-sg', name: 'North Region', cities: [{ id: 'woodlands', name: 'Woodlands' }] },
    { id: 'nes', name: 'North-East Region', cities: [{ id: 'sengkang', name: 'Sengkang' }] },
  ],
};
